### PR TITLE
Change confirmation text before quit

### PR DESCRIPTION
**Pull request by diegopradogesto**
The text doesn't explain what the application does. Change it accordingly to avoid confusion to users. Reported in https://github.com/Ultimaker/Cura/issues/4228

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Maybe we can use the same text as we have when installing plugins?

**Comment by diegopradogesto** [comment]
Do you mean something like: "You will need to restart Cura before changes in packages have effect", but instead... "You will need to restart Cura before your backup is restored."?

**Comment by ChrisTerBeke** [comment]
Something like that would be fine. At least as we use the same phrasing everywhere.

**Comment by ChrisTerBeke** [comment]
Cool thanks. I'll make it part of the next release (which I'll do for the 3.5 release).

**Pull request merged**
